import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home({photos}) {

  const [isLoading, setIsLoading] = useState(false)

  const router = useRouter();

  useEffect(() => {
    console.log(photos);
  }, [])

  if(isLoading) return <p id={styles.loading}>Loading...</p>
  
  return (
    <>
      <Head>
        <title>Photos App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 style={{fontFamily: "sans-serif"}}>All Photos</h1>
        <div className={styles.photos}>
          {
            photos.map((photo) => (
                <div onClick={() => {
                  router.push(`photo/${photo.id}`),
                  setIsLoading(true)
                }} className={styles.photo} key={photo.id}>
                  <p>
                    {
                      photo.id
                    }
                  </p>
                  <p>
                    {
                      `. ${photo.title}`
                    }
                  </p>
                </div>
            ))
          }
        </div>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/photos");
  const data = await res.json();
  return {
    props: {
      photos: data
    }
  }
}